### ISSUE TITLE
Add an Open Source License to the Project

### ISSUE THREAD

**Issue by arthurgubaidullin** [inferst/dudes#33]
Hi,

Thank you for your project! To ensure that other developers can legally use, modify, and distribute your code, please consider adding an open source license. I recommend looking into licenses like MIT щк Apache 2.0, depending on your preferences.

This will help grow the community around the project and attract more contributors.

Thank you!

**Comment by inferst** [comment]
Hi Arthur,

Thank you for the recommendation. I agree it's really important to have a project license.
So I decided to choose MIT. Hope it will help the project to attract more contributors and make the project better.
